---
abstract: 'Redis-backed library for creating background jobs, placing them on multiple queues, and processing them later.'
author:
  - 'Diego Kuperman <diego@freekeylabs.com>'
build_requires:
  Exporter: 0
  File::Temp: 0
  IPC::Cmd: 0
  Test::More: 0.96
  base: 0
  lib: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Resque
requires:
  Carp: 0
  Class::Load: 0
  Data::Compare: 0
  DateTime: 0
  FindBin: 0
  JSON: 0
  List::MoreUtils: 0
  Moose: 0
  Moose::Exporter: 0
  Moose::Role: 0
  Moose::Util: 0
  Moose::Util::TypeConstraints: 0
  POSIX: 0
  Redis: 0
  Scalar::Util: 0
  Sys::Hostname: 0
  Time::HiRes: 0
  Try::Tiny: 0
  namespace::autoclean: 0
  overload: 0
  strict: 0
resources:
  bugtracker: https://github.com/diegok/resque-perl/issues
  homepage: https://github.com/diegok/resque-perl
  repository: https://github.com/diegok/resque-perl.git
version: 0.17
x_Dist_Zilla:
  perl:
    version: 5.018001
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Basic/GatherDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Basic/PruneCruft'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Basic/ManifestSkip'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Basic/MetaYAML'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::License
      name: '@Basic/License'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Basic/Readme'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Basic/ExtraTests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Basic/ExecDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Basic/ShareDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Basic/MakeMaker'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Basic/Manifest'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Basic/TestRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Basic/ConfirmRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Basic/UploadToCPAN'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Git/Check'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Git/Commit'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Git/Tag'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Git/Push'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 2.019
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 5.006
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: 4.005
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: 4.005
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Default/SingleEncoding'
              version: 4.005
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: 4.005
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: 4.005
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: 4.005
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: 4.005
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: 4.005
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: 4.005
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: 4.005
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: 4.005
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: 4.005
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: 4.005
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: 4.005
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: 4.005
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: 4.005
            -
              class: Pod::Weaver::Plugin::Transformer
              name: '-Transformer'
              version: 4.005
      name: PodWeaver
      version: 4.002
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 5.006
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: 0.42
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.006
